const schema = mongoose.Schema({
    _id: String,
    GuildName: String,
    Region: String,
    MemberCount: Number,
    GuildId: Number,
    OwnerId: String,
    Owner: String,
    partnered: Boolean,
    PremiumTier: Number,
    PremiumSubscriptionCount: Number,
    verified: Boolean,
    prefix: { type: String, default: process.env.prefix },
    optin: { type: Boolean, default: false },
    currentlyIn: { type: Boolean, default: true },
    embedColor: { type: String, default: "RANDOM"},
    mutedRole: { type: String, default: undefined},
    logChannel: { type: String, default: undefined},
    welcomeChannel: { type: String, default: undefined},
    welcomemsg: { type: String, default: "**${member.user.username}** Welcome to ***${member.guild.name}***"},
    welcomeopt: { type: Boolean, default: true},
    leaveopt: { type: Boolean, default: true},
    leavemsg: { type: String, default: "**${member.user.username}** Has left ***${member.guild.name}*** welp"}
});
module.exports = mongoose.model("Guild", schema)